<?php

namespace App\Criteria;

use Illuminate\Support\Facades\Auth;
use Prettus\Repository\Contracts\CriteriaInterface;
use Prettus\Repository\Contracts\RepositoryInterface;

/**
 * Class UserCriteria.
 *
 * @package namespace App\Criteria;
 */
class UserCriteria extends CoreCriteria implements CriteriaInterface
{
    /**
     * Fill and sort
     *
     * @param string              $model
     * @param RepositoryInterface $repository
     *
     * @return mixed
     */
//    public function apply($model, RepositoryInterface $repository)
//    {
//        $model = $model->where('name','=', 'ntt' )
//                       ->orderBy('id','desc');
//        return $model;
//    }
//    protected function nameFilter($value)
//    {
//        return $this->builder->where('name', 'like', "%$value%");
//    }
//    public function apply($model, RepositoryInterface $repository)
//    {
//        dd($model);
//        return parent::apply($model, $repository); // TODO: Change the autogenerated stub
//    }
}
